# Economic and Employment Data Analysis

This case study analyzes economic and employment-related data using Pandas.

The dataset contains information about:

- Income
- Employment
- Inflation
- Education
- Population

The analysis includes data cleaning, Pandas operations, descriptive statistics,
grouping, and probability distributions to identify economic patterns.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Create the Dataset

The dataset represents economic and employment indicators for different countries.

In [2]:
data = {
    "Country": ["India", "USA", "Germany", "UK", "Japan", "Canada", "Australia", "France", "Brazil", "China"],

    "Income_USD": [2500, 76000, 95000, 46000, 42000, 55000, 65000, 45000, 11000, 13000],

    "Employment_Rate": [57.0, 60.2, 77.2, 75.1, 78.5, 61.8, 77.0, 68.5, 56.0, 67.5],

    "Inflation_Rate": [5.4, 3.2, 2.1, 3.0, 2.8, 2.9, 3.4, 2.7, 4.6, 2.1],

    "Education_Years": [6.7, 13.7, 14.1, 13.6, 13.5, 13.9, 13.2, 13.4, 8.6, 10.8],

    "Population_Million": [1428, 335, 84, 68, 124, 40, 27, 68, 216, 1410]
}

df = pd.DataFrame(data)
df

,Country,Income_USD,Employment_Rate,Inflation_Rate,Education_Years,Population_Million
0,India,2500,57.0,5.4,6.7,1428
1,USA,76000,60.2,3.2,13.7,335
2,Germany,95000,77.2,2.1,14.1,84
3,UK,46000,75.1,3.0,13.6,68
4,Japan,42000,78.5,2.8,13.5,124
5,Canada,55000,61.8,2.9,13.9,40
6,Australia,65000,77.0,3.4,13.2,27
7,France,45000,68.5,2.7,13.4,68
8,Brazil,11000,56.0,4.6,8.6,216
9,China,13000,67.5,2.1,10.8,1410

## Inspect the Data

Before performing analysis, the dataset is inspected to understand its structure,
data types, and missing values.

In [3]:
df.isnull().sum()

Country               0
Income_USD            0
Employment_Rate       0
Inflation_Rate        0
Education_Years       0
Population_Million    0
dtype: int64

## Data Cleaning

Missing values are checked before analysis.

If missing numerical values are present, they can be replaced using the mean
of the corresponding column.

In [4]:
numeric_columns = ["Income_USD", "Employment_Rate", "Inflation_Rate", "Education_Years", "Population_Million"]

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())

df.isnull().sum()

Country               0
Income_USD            0
Employment_Rate       0
Inflation_Rate        0
Education_Years       0
Population_Million    0
dtype: int64

## Pandas Operations

The income, employment rate, inflation rate, education level, and population
columns are selected for economic analysis.

In [5]:
economic_data = df[["Country","Income_USD", "Employment_Rate", "Inflation_Rate", "Education_Years", "Population_Million"]]
economic_data

,Country,Income_USD,Employment_Rate,Inflation_Rate,Education_Years,Population_Million
0,India,2500,57.0,5.4,6.7,1428
1,USA,76000,60.2,3.2,13.7,335
2,Germany,95000,77.2,2.1,14.1,84
3,UK,46000,75.1,3.0,13.6,68
4,Japan,42000,78.5,2.8,13.5,124
5,Canada,55000,61.8,2.9,13.9,40
6,Australia,65000,77.0,3.4,13.2,27
7,France,45000,68.5,2.7,13.4,68
8,Brazil,11000,56.0,4.6,8.6,216
9,China,13000,67.5,2.1,10.8,1410

## Descriptive Statistics

Descriptive statistics are used to understand the central tendency and
dispersion of the economic variables.

The main measures include:

- Mean
- Standard deviation
- Minimum
- Maximum
- Quartiles

In [6]:
df[["Income_USD", "Employment_Rate", "Inflation_Rate", "Education_Years", "Population_Million"]].describe()

,Income_USD,Employment_Rate,Inflation_Rate,Education_Years,Population_Million
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,45050.000000,67.880000,3.220000,12.150000,380.000000
std,29734.426363,8.761887,1.043285,2.581666,555.395155
min,2500.000000,56.000000,2.100000,6.700000,27.000000
25%,20250.000000,60.600000,2.725000,11.400000,68.000000
50%,45500.000000,68.000000,2.950000,13.450000,104.000000
75%,62500.000000,76.525000,3.350000,13.675000,305.250000
max,95000.000000,78.500000,5.400000,14.100000,1428.000000

## Grouping and Aggregation

Countries are grouped according to their income level.

The income classification is created using the income value.

In [7]:
def income_group(income):
    if income < 10000:
        return "Low Income"
    elif income < 40000:
        return "Middle Income"
    else:
        return "High Income"

df["Income_Group"] = df["Income_USD"].apply(income_group)
df

,Country,Income_USD,Employment_Rate,Inflation_Rate,Education_Years,Population_Million,Income_Group
0,India,2500,57.0,5.4,6.7,1428,Low Income
1,USA,76000,60.2,3.2,13.7,335,High Income
2,Germany,95000,77.2,2.1,14.1,84,High Income
3,UK,46000,75.1,3.0,13.6,68,High Income
4,Japan,42000,78.5,2.8,13.5,124,High Income
5,Canada,55000,61.8,2.9,13.9,40,High Income
6,Australia,65000,77.0,3.4,13.2,27,High Income
7,France,45000,68.5,2.7,13.4,68,High Income
8,Brazil,11000,56.0,4.6,8.6,216,Middle Income
9,China,13000,67.5,2.1,10.8,1410,Middle Income

In [10]:
income_analysis = df.groupby("Income_Group").agg(
    Number_of_Countries=("Country", "count"),
    Average_Income=("Income_USD", "mean"),
    Average_Employment=("Employment_Rate", "mean"),
    Average_Inflation=("Inflation_Rate", "mean"),
    Average_Education=("Education_Years", "mean"),
    Total_Population=("Population_Million", "sum")
)

income_analysis

,Number_of_Countries,Average_Income,Average_Employment,Average_Inflation,Average_Education,Total_Population
Income_Group,,,,,,
High Income,7,60571.428571,71.185714,2.871429,13.628571,746
Low Income,1,2500.000000,57.000000,5.400000,6.700000,1428
Middle Income,2,12000.000000,61.750000,3.350000,9.700000,1626

## Probability of High Employment

A country is considered to have a high employment rate when its employment
rate is greater than 70%.

The probability is calculated as:

$$
P(\text{High Employment})
=
\frac{\text{Number of countries with employment rate > 70}}
{\text{Total number of countries}}
$$

In [11]:
high_employment = (df["Employment_Rate"] > 70).sum()
total_countries = len(df)

probability_high_employment = high_employment / total_countries

print("Probability of high employment:",
      probability_high_employment)

Probability of high employment: 0.4

## Economic Patterns

The grouped results and descriptive statistics can be used to identify
patterns between income, employment, inflation, education, and population.

Higher-income groups can be compared with lower-income groups based on their
average employment, inflation, and education values.

In [12]:
income_analysis

,Number_of_Countries,Average_Income,Average_Employment,Average_Inflation,Average_Education,Total_Population
Income_Group,,,,,,
High Income,7,60571.428571,71.185714,2.871429,13.628571,746
Low Income,1,2500.000000,57.000000,5.400000,6.700000,1428
Middle Income,2,12000.000000,61.750000,3.350000,9.700000,1626