# Case Study 4: Employee Salary and Performance Analysis



Analyze employee salary, experience, department, performance rating,
and job role using Pandas.

The analysis includes:

- Data cleaning
- Grouping
- Aggregation
- Descriptive statistics
- Relationship between experience, salary, and performance.

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Creating the Employee Dataset

The dataset contains employee salary, experience, department,
performance rating, and job role.

Some values are missing so that data cleaning can be performed.

In [2]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Employee_Name": ["Vaisu", "Vikki", "Priya", "Meena", "Leo", "Siri", "Vendhan", "Atena"],
    "Experience_Years": [2, 5, 3, np.nan, 8, 4, 10, 1],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"],
    "Salary": [450000, 650000, 480000, 70000, 85000, np.nan, 95000, 32000],
    "Performance_Rating": [3, 4, 3, 5, 5, 4, 5, 3],
    "Job_Role": ["HR Executive", "Software Engineer", "Accountant",
                 "Software Engineer", "HR Manager", "Financial Analyst",
                 "Senior Engineer", "HR Executive"]
}

df = pd.DataFrame(data)

df

,Employee_ID,Employee_Name,Experience_Years,Department,Salary,Performance_Rating,Job_Role
0,101,Vaisu,2.0,HR,450000.0,3,HR Executive
1,102,Vikki,5.0,IT,650000.0,4,Software Engineer
2,103,Priya,3.0,Finance,480000.0,3,Accountant
3,104,Meena,NaN,IT,70000.0,5,Software Engineer
4,105,Leo,8.0,HR,85000.0,5,HR Manager
5,106,Siri,4.0,Finance,NaN,4,Financial Analyst
6,107,Vendhan,10.0,IT,95000.0,5,Senior Engineer
7,108,Atena,1.0,HR,32000.0,3,HR Executive

## Data Cleaning

First, missing values are identified.

Missing numerical values are handled using the mean of the
corresponding column.

In [4]:
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Experience_Years      1
Department            0
Salary                1
Performance_Rating    0
Job_Role              0
dtype: int64

## Filling Missing Value

In [5]:
df["Experience_Years"] = df["Experience_Years"].fillna(df["Experience_Years"].mean())

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

,Employee_ID,Employee_Name,Experience_Years,Department,Salary,Performance_Rating,Job_Role
0,101,Vaisu,2.000000,HR,450000.0,3,HR Executive
1,102,Vikki,5.000000,IT,650000.0,4,Software Engineer
2,103,Priya,3.000000,Finance,480000.0,3,Accountant
3,104,Meena,4.714286,IT,70000.0,5,Software Engineer
4,105,Leo,8.000000,HR,85000.0,5,HR Manager
5,106,Siri,4.000000,Finance,266000.0,4,Financial Analyst
6,107,Vendhan,10.000000,IT,95000.0,5,Senior Engineer
7,108,Atena,1.000000,HR,32000.0,3,HR Executive

In [7]:
# Checking again
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Experience_Years      0
Department            0
Salary                0
Performance_Rating    0
Job_Role              0
dtype: int64

## Department-wise Analysis

Employees are grouped according to their department.

The following values are calculated:

- Number of employees
- Average salary
- Average experience
- Average performance rating

In [9]:
department_analysis = df.groupby("Department").agg(
    Employee_Count=("Employee_ID", "count"),
    Average_Salary=("Salary", "mean"),
    Average_Experience=("Experience_Years", "mean"),
    Average_Performance=("Performance_Rating", "mean")
)

department_analysis

,Employee_Count,Average_Salary,Average_Experience,Average_Performance
Department,,,,
Finance,2,373000.000000,3.500000,3.500000
HR,3,189000.000000,3.666667,3.666667
IT,3,271666.666667,6.571429,4.666667

## Grouping by Job Role

Employees are grouped according to their job role.

The average salary and performance rating are calculated
for each job role.

In [10]:
role_analysis = df.groupby("Job_Role").agg(
    Employee_Count=("Employee_ID", "count"),
    Average_Salary=("Salary", "mean"),
    Average_Performance=("Performance_Rating", "mean")
)

role_analysis

                   Employee_Count  Average_Salary  Average_Performance
Job_Role
Accountant                      1        480000.0                  3.0
Financial Analyst               1        266000.0                  4.0
HR Executive                    2        241000.0                  3.0
HR Manager                      1         85000.0                  5.0
Senior Engineer                 1         95000.0                  5.0
Software Engineer               2        360000.0                  4.5

## Salary and Performance Aggregation

Aggregation is used to calculate overall salary and
performance measures.

In [11]:
salary_performance = df.agg(
    Average_Salary=("Salary", "mean"),
    Maximum_Salary=("Salary", "max"),
    Minimum_Salary=("Salary", "min"),
    Average_Performance=("Performance_Rating", "mean")
)

salary_performance

                       Salary  Performance_Rating
Average_Salary       266000.0                 NaN
Maximum_Salary       650000.0                 NaN
Minimum_Salary        32000.0                 NaN
Average_Performance       NaN                 4.0

## Descriptive Statistical Analysis

Descriptive statistics are calculated for:

- Experience
- Salary
- Performance rating

The `describe()` function provides count, mean, standard deviation,
minimum, quartiles, and maximum.

In [12]:
df[["Experience_Years", "Salary", "Performance_Rating"]].describe()

       Experience_Years         Salary  Performance_Rating
count          8.000000       8.000000             8.00000
mean           4.714286  266000.000000             4.00000
std            3.010187  233691.493824             0.92582
min            1.000000   32000.000000             3.00000
25%            2.750000   81250.000000             3.00000
50%            4.357143  180500.000000             4.00000
75%            5.750000  457500.000000             5.00000
max           10.000000  650000.000000             5.00000

## Relationship Between Experience, Salary and Performance

The correlation between experience, salary, and performance
is calculated to study their relationship.

The correlation coefficient ranges from -1 to +1.

- Positive value → positive relationship
- Negative value → negative relationship
- Value close to 0 → weak or no linear relationship

## Correlation Between Experience, Salary and Performance

The Pearson correlation coefficient between two variables is given by:

$$
r_{XY}
=
\frac{
\sum_{i=1}^{n}(X_i-\bar{X})(Y_i-\bar{Y})
}{
\sqrt{
\sum_{i=1}^{n}(X_i-\bar{X})^2
\sum_{i=1}^{n}(Y_i-\bar{Y})^2
}
}
$$

The correlation matrix calculates the correlation between:

- **Experience and Salary**
- **Experience and Performance**
- **Salary and Performance**

The value of $r$ ranges from $-1$ to $+1$.

$$
-1 \leq r \leq +1
$$

A positive value indicates a positive relationship, while a negative value
indicates a negative relationship.

In [13]:
relationship = df[["Experience_Years", "Salary", "Performance_Rating"]].corr()
relationship

                    Experience_Years    Salary  Performance_Rating
Experience_Years            1.000000 -0.281468            0.856781
Salary                     -0.281468  1.000000           -0.470124
Performance_Rating          0.856781 -0.470124            1.000000