# Case Study 3: Sales and Customer Analysis

Analyze product sales, prices, quantities, revenue, and customer information. Use
grouping and aggregation to identify sales patterns and summarize business
performance.

In [1]:
import pandas as pd

In [3]:
data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "Customer_Name": ["Vaisu", "Vikki", "Vendhan", "Siri", "Priya","Perumal", "Atena", "Leo", "Vaisu", "Vikki"],
    "Region": ["South", "North", "South", "East", "West", "North", "East", "West", "South", "North"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet", "Laptop"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics",
                 "Electronics", "Electronics", "Electronics", "Electronics",
                 "Electronics", "Electronics"],
    "Price": [55000, 20000, 30000, 50000, 18000, 32000, 60000, 22000, 28000, 58000],
    "Quantity": [2, 5, 2, 1, 3, 4, 2, 6, 3, 2],
    "Customer_Type": ["New", "Returning", "New", "Returning", "New", "Returning", "New", "Returning", "Returning", "New"]
}

df = pd.DataFrame(data)

df

,Order_ID,Customer_Name,Region,Product,Category,Price,Quantity,Customer_Type
0,1001,Vaisu,South,Laptop,Electronics,55000,2,New
1,1002,Vikki,North,Mobile,Electronics,20000,5,Returning
2,1003,Vendhan,South,Tablet,Electronics,30000,2,New
3,1004,Siri,East,Laptop,Electronics,50000,1,Returning
4,1005,Priya,West,Mobile,Electronics,18000,3,New
5,1006,Perumal,North,Tablet,Electronics,32000,4,Returning
6,1007,Atena,East,Laptop,Electronics,60000,2,New
7,1008,Leo,West,Mobile,Electronics,22000,6,Returning
8,1009,Vaisu,South,Tablet,Electronics,28000,3,Returning
9,1010,Vikki,North,Laptop,Electronics,58000,2,New

## Calculate Revenue

Revenue is calculated using price and quantity.

$$
\text{Revenue}
=
\text{Price} \times \text{Quantity}
$$

In [4]:
df["Revenue"] = df["Price"] * df["Quantity"]
df

,Order_ID,Customer_Name,Region,Product,Category,Price,Quantity,Customer_Type,Revenue
0,1001,Vaisu,South,Laptop,Electronics,55000,2,New,110000
1,1002,Vikki,North,Mobile,Electronics,20000,5,Returning,100000
2,1003,Vendhan,South,Tablet,Electronics,30000,2,New,60000
3,1004,Siri,East,Laptop,Electronics,50000,1,Returning,50000
4,1005,Priya,West,Mobile,Electronics,18000,3,New,54000
5,1006,Perumal,North,Tablet,Electronics,32000,4,Returning,128000
6,1007,Atena,East,Laptop,Electronics,60000,2,New,120000
7,1008,Leo,West,Mobile,Electronics,22000,6,Returning,132000
8,1009,Vaisu,South,Tablet,Electronics,28000,3,Returning,84000
9,1010,Vikki,North,Laptop,Electronics,58000,2,New,116000

## Product-wise Sales Analysis

Group the data by product and calculate:

- Total quantity sold
- Total revenue
- Average price

In [5]:
product_analysis = df.groupby("Product").agg(
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("Revenue", "sum"),
    Average_Price=("Price", "mean")
)

product_analysis

         Total_Quantity  Total_Revenue  Average_Price
Product
Laptop                7         396000        55750.0
Mobile               14         286000        20000.0
Tablet                9         272000        30000.0

## Customer-wise Sales Analysis

Group the data by customer and calculate:

- Number of orders
- Total quantity purchased
- Total revenue

In [6]:
customer_analysis = df.groupby("Customer_Name").agg(
    Number_of_Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("Revenue", "sum")
)

customer_analysis

               Number_of_Orders  Total_Quantity  Total_Revenue
Customer_Name
Atena                         1               2         120000
Leo                           1               6         132000
Perumal                       1               4         128000
Priya                         1               3          54000
Siri                          1               1          50000
Vaisu                         2               5         194000
Vendhan                       1               2          60000
Vikki                         2               7         216000

## Region-wise Sales Analysis

Group the data by region and calculate:

- Number of orders
- Total quantity sold
- Total revenue

In [7]:
region_analysis = df.groupby("Region").agg(
    Number_of_Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("Revenue", "sum")
)

region_analysis

        Number_of_Orders  Total_Quantity  Total_Revenue
Region
East                   2               3         170000
North                  3              11         344000
South                  3               7         254000
West                   2               9         186000

##  Identifying Sales Patterns

Sort the product and customer analysis by total revenue
to identify the highest revenue-generating products and customers.

In [8]:
product_analysis.sort_values(by="Total_Revenue", ascending=False)

         Total_Quantity  Total_Revenue  Average_Price
Product
Laptop                7         396000        55750.0
Mobile               14         286000        20000.0
Tablet                9         272000        30000.0

In [9]:
customer_analysis.sort_values(by="Total_Revenue", ascending=False)

               Number_of_Orders  Total_Quantity  Total_Revenue
Customer_Name
Vikki                         2               7         216000
Vaisu                         2               5         194000
Leo                           1               6         132000
Perumal                       1               4         128000
Atena                         1               2         120000
Vendhan                       1               2          60000
Priya                         1               3          54000
Siri                          1               1          50000

## Business Performance Summary

Calculate the total quantity sold and total revenue
to summarize overall business performance.

* **Total quantity sold** → How many products were sold overall.
* **Total revenue** → How much money was generated from sales.
* **Best-selling product** → Which product sold the highest quantity.
* **Highest revenue product** → Which product generated the most revenue.
* **Top customer** → Which customer generated the most revenue.
* **Best-performing region** → Which region generated the most revenue.

In [10]:
business_summary = df.agg(Total_Quantity_Sold=("Quantity", "sum"), Total_Revenue=("Revenue", "sum"))
business_summary

                     Quantity   Revenue
Total_Quantity_Sold      30.0       NaN
Total_Revenue             NaN  954000.0

In [16]:
business_summary = pd.DataFrame({
    "Metric": ["Total Quantity Sold", "Total Revenue"],
    "Value": [df["Quantity"].sum(), df["Revenue"].sum()]
})

business_summary

                Metric   Value
0  Total Quantity Sold      30
1        Total Revenue  954000

Business performance summary = overall results of the sales data