# Student Academic Performance Analysis

> **Student Academic Performance Analysis Analyze student marks, attendance, and grades using Pandas. Perform data cleaning, indexing, grouping, aggregation, and descriptive statistical analysis**


##  Mathematical Formulation
### 1. Mean (Average Marks)
$$
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i
$$

### 2. Standard Deviation
$$
\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2}
$$

### 3. Total Marks
$$
\text{Total} = \sum_{k=1}^{m} \text{Subject}_k
$$

### 4. Percentage
$$
\text{Percentage} = \left(\frac{\text{Total Marks Obtained}}{\text{Total Maximum Marks}}\right) \times 100
$$

### 5. Attendance Ratio
$$
\text{Attendance Ratio} = \frac{\text{Classes Attended}}{\text{Total Classes}} \times 100
$$

## 2. Dataset Description

The dataset contains information about students and their academic
performance.

| Column | Description |
|---|---|
| Student_ID | Unique identification number of the student |
| Name | Name of the student |
| Gender | Gender of the student |
| Attendance | Attendance percentage |
| Mathematics | Marks obtained in Mathematics |
| Physics | Marks obtained in Physics |
| Chemistry | Marks obtained in Chemistry |
| Social_Science | Marks obtained in Social_Science |
| German | Marks obtained in German |
| Grade | Overall academic grade |

The marks are assumed to be out of 100 and attendance is represented
as a percentage.

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Vendhan", "Vikki", "Vaisu", "Siri",
             "Sangeeth", "Priya", "Perumal", "Atena"],
    "Gender": ["M", "M", "F", "F", "M", "F", "M", "F"],
    "Attendance_%": [90, 85, 70, 95, 98, 60, 82, np.nan],
    "Mathematics": [100, 92, np.nan, 91, 60, 95, 74, 81],
    "Physics": [98, 90, 95, 89, 62, 92, 75, 83],
    "Chemistry": [97, 91, 93, 90, np.nan, 94, 72, 80],
    "Social_Science": [95, 93, 94, 92, 64, 91, 78, 86],
    "German": [92, 88, 90, 87, 60, 89, np.nan, 82],
    "Grade": ["A", "A", "A", "A", "C", "A", "B", "B"]
}

df = pd.DataFrame(data)
df

,Student_ID,Name,Gender,Attendance_%,Mathematics,Physics,Chemistry,Social_Science,German,Grade
0,101,Vendhan,M,90.0,100.0,98,97.0,95,92.0,A
1,102,Vikki,M,85.0,92.0,90,91.0,93,88.0,A
2,103,Vaisu,F,70.0,NaN,95,93.0,94,90.0,A
3,104,Siri,F,95.0,91.0,89,90.0,92,87.0,A
4,105,Sangeeth,M,98.0,60.0,62,NaN,64,60.0,C
5,106,Priya,F,60.0,95.0,92,94.0,91,89.0,A
6,107,Perumal,M,82.0,74.0,75,72.0,78,NaN,B
7,108,Atena,F,NaN,81.0,83,80.0,86,82.0,B

In [3]:
print("Shape of dataset:", df.shape)

df.head()

Shape of dataset: (8, 10)

,Student_ID,Name,Gender,Attendance_%,Mathematics,Physics,Chemistry,Social_Science,German,Grade
0,101,Vendhan,M,90.0,100.0,98,97.0,95,92.0,A
1,102,Vikki,M,85.0,92.0,90,91.0,93,88.0,A
2,103,Vaisu,F,70.0,NaN,95,93.0,94,90.0,A
3,104,Siri,F,95.0,91.0,89,90.0,92,87.0,A
4,105,Sangeeth,M,98.0,60.0,62,NaN,64,60.0,C

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      8 non-null      int64
 1   Name            8 non-null      object
 2   Gender          8 non-null      object
 3   Attendance_%    7 non-null      float64
 4   Mathematics     7 non-null      float64
 5   Physics         8 non-null      int64
 6   Chemistry       7 non-null      float64
 7   Social_Science  8 non-null      int64
 8   German          7 non-null      float64
 9   Grade           8 non-null      object
dtypes: float64(4), int64(3), object(3)
memory usage: 772.0+ bytes

## **Data Cleaning**

> Data cleaning is the process of identifying and correcting missing,
incorrect, or inconsistent data.

> First, we check whether the dataset contains missing values.

## Handling Missing Values


We first detect missing values and then replace them with
appropriate values.

For numerical data, mean or median can be used depending
on the characteristics of the data.

In [5]:
df.isnull().sum()

Student_ID        0
Name              0
Gender            0
Attendance_%      1
Mathematics       1
Physics           0
Chemistry         1
Social_Science    0
German            1
Grade             0
dtype: int64

In [6]:
df["Attendance_%"] = df["Attendance_%"].fillna(df["Attendance_%"].mean())

df["Mathematics"] = df["Mathematics"].fillna(df["Mathematics"].mean())

df["Chemistry"] = df["Chemistry"].fillna(df["Chemistry"].mean())

df["German"] = df["German"].fillna(df["German"].mean())

df

,Student_ID,Name,Gender,Attendance_%,Mathematics,Physics,Chemistry,Social_Science,German,Grade
0,101,Vendhan,M,90.000000,100.000000,98,97.000000,95,92.0,A
1,102,Vikki,M,85.000000,92.000000,90,91.000000,93,88.0,A
2,103,Vaisu,F,70.000000,84.714286,95,93.000000,94,90.0,A
3,104,Siri,F,95.000000,91.000000,89,90.000000,92,87.0,A
4,105,Sangeeth,M,98.000000,60.000000,62,88.142857,64,60.0,C
5,106,Priya,F,60.000000,95.000000,92,94.000000,91,89.0,A
6,107,Perumal,M,82.000000,74.000000,75,72.000000,78,84.0,B
7,108,Atena,F,82.857143,81.000000,83,80.000000,86,82.0,B

In [7]:
# Check missing values AFTER cleaning
df.isnull().sum()

Student_ID        0
Name              0
Gender            0
Attendance_%      0
Mathematics       0
Physics           0
Chemistry         0
Social_Science    0
German            0
Grade             0
dtype: int64

Since the dataset does not contain missing values or duplicate records,
no major cleaning operation is required.

## **Indexing and Selection**

The `Student_ID` column uniquely identifies each student.

It can be used as the DataFrame index to make student-level analysis
more convenient.


Pandas provides two important indexing methods:

- `loc[]` → label-based indexing
- `iloc[]` → position-based indexing

`iloc[]` works like normal Python positional indexing,
while `loc[]` selects data using labels.

In [8]:
df_indexed = df.set_index("Student_ID")

df_indexed

,Name,Gender,Attendance_%,Mathematics,Physics,Chemistry,Social_Science,German,Grade
Student_ID,,,,,,,,,
101,Vendhan,M,90.000000,100.000000,98,97.000000,95,92.0,A
102,Vikki,M,85.000000,92.000000,90,91.000000,93,88.0,A
103,Vaisu,F,70.000000,84.714286,95,93.000000,94,90.0,A
104,Siri,F,95.000000,91.000000,89,90.000000,92,87.0,A
105,Sangeeth,M,98.000000,60.000000,62,88.142857,64,60.0,C
106,Priya,F,60.000000,95.000000,92,94.000000,91,89.0,A
107,Perumal,M,82.000000,74.000000,75,72.000000,78,84.0,B
108,Atena,F,82.857143,81.000000,83,80.000000,86,82.0,B

Now Student_ID becomes the row label.

In [9]:
df_indexed.loc[102]

Name              Vikki
Gender                M
Attendance_%       85.0
Mathematics        92.0
Physics              90
Chemistry          91.0
Social_Science       93
German             88.0
Grade                 A
Name: 102, dtype: object

This retrieves the student whose Student_ID is 102.

In [10]:
df_indexed.iloc[1]

Name              Vikki
Gender                M
Attendance_%       85.0
Mathematics        92.0
Physics              90
Chemistry          91.0
Social_Science       93
German             88.0
Grade                 A
Name: 102, dtype: object

This retrieves the second row because Python positions start from 0.

## Calculating Average Marks

The average mark of each student can be calculated using the arithmetic
mean.

### Academic Performance Calculation

Each student has marks in five subjects:

1. Mathematics
2. Physics
3. Chemistry
4. Social Science
5. German

The total marks are calculated as:

$$
\text{Total Marks}
=
M + P + C + SS + G
$$

The average mark is:

$$
\text{Average Marks}
=
\frac{\text{Total Marks}}{5}
$$

In [11]:
subjects = ["Mathematics", "Physics", "Chemistry", "Social_Science", "German"]

df["Total_Marks"] = df[subjects].sum(axis=1)

df["Average_Marks"] = df["Total_Marks"] / len(subjects)

df

,Student_ID,Name,Gender,Attendance_%,Mathematics,Physics,Chemistry,Social_Science,German,Grade,Total_Marks,Average_Marks
0,101,Vendhan,M,90.000000,100.000000,98,97.000000,95,92.0,A,482.000000,96.400000
1,102,Vikki,M,85.000000,92.000000,90,91.000000,93,88.0,A,454.000000,90.800000
2,103,Vaisu,F,70.000000,84.714286,95,93.000000,94,90.0,A,456.714286,91.342857
3,104,Siri,F,95.000000,91.000000,89,90.000000,92,87.0,A,449.000000,89.800000
4,105,Sangeeth,M,98.000000,60.000000,62,88.142857,64,60.0,C,334.142857,66.828571
5,106,Priya,F,60.000000,95.000000,92,94.000000,91,89.0,A,461.000000,92.200000
6,107,Perumal,M,82.000000,74.000000,75,72.000000,78,84.0,B,383.000000,76.600000
7,108,Atena,F,82.857143,81.000000,83,80.000000,86,82.0,B,412.000000,82.400000

>> axis=1 means the calculation is performed row-wise.

Therefore, the five subject marks of each student are added together.

## Filtering Students

Boolean conditions can be used to select specific students.

For example, students with an average mark of at least 80
can be identified using a filtering condition.

In [12]:
Top_scorers = df[df["Average_Marks"] >= 80]

Top_scorers[["Student_ID", "Name", "Average_Marks", "Grade"]]

   Student_ID     Name  Average_Marks Grade
0         101  Vendhan      96.400000     A
1         102    Vikki      90.800000     A
2         103    Vaisu      91.342857     A
3         104     Siri      89.800000     A
5         106    Priya      92.200000     A
7         108    Atena      82.400000     B

## Grouping and Aggregation

The `groupby()` function is used to divide the data into groups based
on a categorical variable.

- Number of students
- Average attendance
- Average marks

In [14]:
gender_analysis = df.groupby("Gender").agg(
    Student_Count=("Student_ID", "count"),
    Average_Attendance=("Attendance_%", "mean"),
    Average_Marks=("Average_Marks", "mean")
)

gender_analysis

        Student_Count  Average_Attendance  Average_Marks
Gender
F                   4           76.964286      88.935714
M                   4           88.750000      82.657143

**Interpretation**

> This allows us to compare academic and attendance statistics between the M and F groups without manually calculating each group.

## Grouping Students by Grade

Students are grouped according to their final grade.

The analysis calculates:

- Number of students
- Average marks
- Average attendance

In [15]:
grade_analysis = df.groupby("Grade").agg(
    Student_Count=("Student_ID", "count"),
    Average_Marks=("Average_Marks", "mean"),
    Average_Attendance=("Attendance_%", "mean")
)

grade_analysis

       Student_Count  Average_Marks  Average_Attendance
Grade
A                  5      92.108571           80.000000
B                  2      79.500000           82.428571
C                  1      66.828571           98.000000

## Descriptive Statistical Analysis

Descriptive statistics are used to summarize the characteristics of
the dataset


- Mean
- Median
- Standard deviation
- Minimum
- Maximum
- Quartiles

The `describe()` function provides these statistics for
numerical columns.

In [16]:
df[["Attendance_%","Mathematics","Physics","Chemistry","Social_Science","German","Total_Marks","Average_Marks"]].describe()

,Attendance_%,Mathematics,Physics,Chemistry,Social_Science,German,Total_Marks,Average_Marks
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
mean,82.857143,84.714286,85.500000,88.142857,86.625000,84.000000,428.982143,85.796429
std,12.653950,12.936264,11.892375,8.236306,10.689614,10.212038,49.322491,9.864498
min,60.000000,60.000000,62.000000,72.000000,64.000000,60.000000,334.142857,66.828571
25%,79.000000,79.250000,81.000000,86.107143,84.000000,83.500000,404.750000,80.950000
50%,83.928571,87.857143,89.500000,90.500000,91.500000,87.500000,451.500000,90.300000
75%,91.250000,92.750000,92.750000,93.250000,93.250000,89.250000,457.785714,91.557143
max,98.000000,100.000000,98.000000,97.000000,95.000000,92.000000,482.000000,96.400000